### ISSUE TITLE
Editor tab layouts left or right break

### ISSUE THREAD

**Issue by ExaInsanity** [austinstanding/midnight-lights-vstheme#1]
The theme works fine with editor tabs on top: 
![image](https://user-images.githubusercontent.com/61018569/124123576-c1a96680-da77-11eb-9141-eb937f978209.png)

However, setting the tab layout to left or right, commonly used when dealing with large quantities of files, the theme only applies the glyph foreground color, but not the dark background: 
![image](https://user-images.githubusercontent.com/61018569/124123716-e8679d00-da77-11eb-8ddc-ea64ee14f83e.png)

**Comment by austinstanding** [comment]
Thank you for sharing, that's certainly not intentional or desired. Midnight Lights pre-dates vertical document tabs and support was never added.

This raises an important point, there are entire categories of newer theme elements missing from the `.vstheme`. When Visual Studio adds a new feature there is no public facing documentation *(that I know of)* to share new elements introduced, nor are tools provided to import them into older themes.

I'll prioritize adding support, I also want to make another quality pass with the lessons I've learned working on my second theme. Sadly as that was a fork of this, it also suffers from the dated `.vstheme` missing elements.

**Comment by austinstanding** [comment]
I've updated the theme with all the missing elements from the standard dark theme, so any missing theming will be at least a little less jarring. fd4212b5cc8bdb2edeba69992a80953183661e2f

I've also applied styling to the relevant FileTab attributes to align with the theme. I had a hard choice between the outer shell charcoal and the inner environment midnight blue. I chose to match the outer shell as trying to match the environment had the undesirable side-effect of applying the blue while in the top layout, bleeding over into the commandbar space. b0b7464dd30300cbeae3a003fc4ca0e64f90761d
![Screenshot 2021-07-02 192918](https://user-images.githubusercontent.com/22038786/124339798-14fde080-db6e-11eb-9809-284fe5fad292.png)

The changes are already pushed to the marketplace, simply update your extension to 1.3.0 ✌️
